apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-config
  labels:
    component: filebeat
data:
  conf.yaml: |
    filebeat.inputs:
    - type: log
      paths:
        - '/app/logs/*.log'
    output:
      logstash:
        hosts: [ "logstash:5044" ]