apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
  labels:
    component: grafana
data:
  datasource.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        url: http://prometheus:9090
        isDefault: true
        access: proxy
        editable: true