apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: grafana
  name: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: grafana
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.31.2 (a92241f79)
      creationTimestamp: null
      labels:
        io.kompose.network/docker-default: "true"
        io.kompose.service: grafana
    spec:
      containers:
        - env:
            - name: GF_SECURITY_ADMIN_PASSWORD
              value: grafana
            - name: GF_SECURITY_ADMIN_USER
              value: admin
          # image: grafana/grafana debería ser la versión que hemos usado en Docker file y no latest
          image: alejandropalmier/grafana:1.0
          name: grafana
          ports:
            - containerPort: 3000
              # hostPort: 3000
              protocol: TCP
          resources: {}
          # args:
          #   - -c
          #   - umask 000
          #   - -e
          volumeMounts:
            - mountPath: /etc/grafana/provisioning/datasources
              name: grafana-config

            - mountPath: /var/lib/grafana
              name: grafana-claim0
      restartPolicy: Always
      volumes:
        # - name: grafana-data
        #   hostPath:
        #     path: /mnt/grafana/grafana-storage
        #     type: DirectoryOrCreate
        - name: grafana-claim0
          persistentVolumeClaim:
            claimName: grafana-claim0

        - name: grafana-config
          configMap:
            name: grafana-config
status: {}
