apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
  labels:
    component: kibana
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      component: kibana
  template:
    metadata:
      labels:
        component: kibana
    spec:
      containers:
        - name: kibana
          image: kibana:8.12.2
          ports:
            - containerPort: 5601

          # volumeMounts:
          #   - mountPath: /usr/share/kibana/config
          #     name: kibana-claim0

      restartPolicy: Always
      # volumes:
      #   - name: kibana-claim0
      #     persistentVolumeClaim:
      #       claimName: kibana-claim0