apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: prometheus
  name: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: prometheus
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.31.2 (a92241f79)
      creationTimestamp: null
      labels:
        io.kompose.network/docker-default: "true"
        io.kompose.service: prometheus
    spec:
      containers:
        - image: bitnami/prometheus:2.50.1
          name: prometheus
          ports:
            - containerPort: 9090
              # hostPort: 9090
              protocol: TCP
          resources: {}
          volumeMounts:
            - mountPath: /opt/bitnami/prometheus/conf
              name: prometheus-config
            - mountPath: /opt/bitnami/prometheus/data
              name: prometheus-claim0
      restartPolicy: Always
      volumes:
        - name: prometheus-config
          configMap:
            name: prometheus-config
        - name: prometheus-claim0
          persistentVolumeClaim:
            claimName: prometheus-claim0
        # - name: prometheus-data
        #   hostPath:
        #     path: /mnt/prometheus/prometheus-persistence
        #     type: DirectoryOrCreate
status: {}
