apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: web
  name: web
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: web
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.31.2 (a92241f79)
      creationTimestamp: null
      labels:
        io.kompose.network/docker-default: "true"
        io.kompose.service: web
    spec:
      containers:
        # - image: nginx:1.25.4-alpine
        - image: alejandropalmier/web-portal:1.0
          name: web
          ports:
            - containerPort: 80
              # hostPort: 80
              protocol: TCP
          resources: {}
          # volumeMounts:
          #   - mountPath: /usr/share/nginx/html
          #     name: web-claim0
      restartPolicy: Always
      # volumes:
      #   - name: web-claim0
      #     persistentVolumeClaim:
      #       claimName: web-claim0
status: {}
